### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by phil123456** [gitbls/RPiVNCHowTo#4]
Hi,

running make-systemd-xvnc, it does not find /bin bash

regards

**Comment by gitbls** [comment]
Phil, thanks for taking a look at this. I can assure you that this script works, since your system would be quite dead in the water if /bin/bash was not present on your system.

Here are a couple of things that would help in sorting out the root cause:

- Please outline how you downloaded the script to your Linux system. Was there a Windows system involved in the download process?
- Please provide the output from `od -b make-system-xvnc | head`. This will show whether the file is corrupted in some way.

**Comment by phil123456** [comment]
my bad, I copied a repo cloned on windows

you can close this request

**Comment by gitbls** [comment]
Closed per request.
