### ISSUE TITLE
How to make it work for the sddm display manager?

### ISSUE THREAD

**Issue by igormiktor** [gitbls/RPiVNCHowTo#7]
Hi,

Love your guide and the bash scripts.  Works great on my RPi 3B.  In fact, I liked it so much on my RPi that I wanted to set up TigerVNC similarly in "on demand" mode on my Kubuntu 20.04 primary desktop system.  The problem I have is that Kubuntu 20.04 uses sddm as the display manager and I haven't figured out what the analogous modifications need to be to those you list for lightdm and xdm.  

I did create a single systemd socket/service pair using the make-systemd-xvnc script (this is for port 5901).  When I connect my VNC client to localhost:5901 I do "connect" but just get a black screen.  I say it "connects" because there is no error, while attempting localhost:5902 produces an explicit "unable to connect to VNC server" message.  

This is why I infer that there is some tweak I need to make to the sddm configuration.  But I'm not sure what in the sddm configuration I need to tweak (the modifications for lightdm and xdm don't seem to have any commonalities I can use as clues for sddm).

Any chance you can point me in the right direction?  Thanks!

Igor

**Comment by gitbls** [comment]
I looked into sddm (along with other display managers) a couple of years ago when I was sorting all this out, and found that sddm was missing XDMCP support (see, for example [here](https://github.com/sddm/sddm/issues/1180) and [here](https://github.com/sddm/sddm/issues/1069). 

I'm pretty sure that there's not a way to make sddm (or any display manager, for that matter) work without XDMCP support. The typical result if XDMCP is not enabled (or can't be enabled) is a blank (black) screen, as you've discovered.

Sadly, since the sddm devs (whoever they are) have decided to not support XDMCP, I think your choices are: use an different , but XDMCP-compliant display manager, or not have dynamic virtual VNC desktops.

I've been using xdm for a really long time, and while it's not the prettiest display manager, it is small, fast, and supports XDMCP...3 very positive attributes IMHO. 

Sorry I don't have a better answer for you.

**Comment by igormiktor** [comment]
Thank you for the information.  That's a rather unfortunate situation, but it is what it is.  Embarrassing to admit, but I remember xdm from late 80s and early 90s... 

Thank you again!

**Comment by gitbls** [comment]
Sadly, closing this without a way to enable sddm support. 😥
